# Generated by Django 3.2.14 on 2023-01-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20, verbose_name='用水量')),
                ('year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20)),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.table1')),
            ],
        ),
        migrations.CreateModel(
            name='table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.CharField(default='', max_length=20)),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.table2')),
            ],
        ),
        migrations.CreateModel(
            name='table4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.CharField(default='', max_length=20)),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.table3')),
            ],
        ),
    ]
