# Generated by Django 3.2.14 on 2022-11-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221122_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='消耗',
            name='用电量',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='用电量(kw.h)'),
        ),
    ]
