# Generated by Django 3.2.14 on 2022-11-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_消耗_用电量'),
    ]

    operations = [
        migrations.AddField(
            model_name='消耗',
            name='用水量计划',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用水量计划(m3)'),
        ),
        migrations.AddField(
            model_name='消耗',
            name='用电量计划',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用电量计划(kw.h)'),
        ),
    ]
