# Generated by Django 3.2.14 on 2022-12-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_levelone_levelthree_leveltwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelone',
            name='title',
            field=models.CharField(max_length=50, verbose_name='厂区名'),
        ),
        migrations.AlterField(
            model_name='levelone',
            name='year',
            field=models.IntegerField(verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='levelthree',
            name='title',
            field=models.CharField(max_length=50, verbose_name='厂区名'),
        ),
        migrations.AlterField(
            model_name='leveltwo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='厂区名'),
        ),
        migrations.CreateModel(
            name='LevelFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='厂区名')),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.levelthree')),
            ],
        ),
    ]
