# Generated by Django 3.2.14 on 2022-12-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221206_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('月份', models.CharField(choices=[('1', '一月份'), ('2', '二月份'), ('3', '三月份'), ('4', '四月份'), ('5', '五月份'), ('6', '六月份'), ('7', '七月份'), ('8', '八月份'), ('9', '九月份'), ('10', '十月份'), ('11', '十一月份'), ('12', '十二月份')], max_length=10)),
                ('用水量', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='用水量(m3)')),
                ('金额1', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='金额(元)')),
                ('用电量', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='用电量(kw.h)')),
                ('金额2', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='金额(元)')),
                ('用水量计划', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用水量计划(m3)')),
                ('用电量计划', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用电量计划(kw.h)')),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.levelfour')),
            ],
        ),
    ]
