# Generated by Django 3.2.14 on 2022-12-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_levelfive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelfive',
            name='用水量',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用水量(m3)'),
        ),
        migrations.AlterField(
            model_name='levelfive',
            name='用电量',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='用电量(kw.h)'),
        ),
    ]
