# Generated by Django 3.2.14 on 2022-11-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='厂区',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('厂区名', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='消耗',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('月份', models.CharField(choices=[(1, '一月份'), (2, '二月份'), (3, '三月份'), (4, '四月份'), (5, '一月份'), (6, '二月份'), (7, '三月份'), (8, '四月份'), (9, '一月份'), (10, '二月份'), (11, '三月份'), (12, '四月份')], max_length=10)),
                ('用水量', models.IntegerField()),
                ('金额1', models.IntegerField()),
                ('用电量', models.IntegerField()),
                ('金额2', models.IntegerField()),
                ('bind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.厂区')),
            ],
        ),
    ]
