# Generated by Django 3.2.14 on 2022-11-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='厂区',
            name='年度',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='月份',
            field=models.CharField(choices=[('1', '一月份'), ('2', '二月份'), ('3', '三月份'), ('4', '四月份'), ('5', '五月份'), ('6', '六月份'), ('7', '七月份'), ('8', '八月份'), ('9', '九月份'), ('10', '十月份'), ('11', '十一月份'), ('12', '十二月份')], max_length=10),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='用水量',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='用电量',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='金额1',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='金额2',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
