# Generated by Django 3.2.14 on 2022-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221121_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='消耗',
            old_name='金额1',
            new_name='用电金额',
        ),
        migrations.RemoveField(
            model_name='消耗',
            name='金额2',
        ),
        migrations.AddField(
            model_name='消耗',
            name='用水金额',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=1000000, verbose_name='用水量(M3)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='消耗',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
