# Generated by Django 3.2.14 on 2022-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221122_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='消耗',
            name='用水金额',
        ),
        migrations.RemoveField(
            model_name='消耗',
            name='用电金额',
        ),
        migrations.AddField(
            model_name='消耗',
            name='金额1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='金额(元)'),
        ),
        migrations.AddField(
            model_name='消耗',
            name='金额2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='金额(元)'),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='用水量',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='用水量(m3)'),
        ),
        migrations.AlterField(
            model_name='消耗',
            name='用电量',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='用水量(kw.h)'),
        ),
    ]
